### ISSUE TITLE
Deploy -- `canari install-package` doesn't exist anymore?

### ISSUE THREAD

**Issue by zmallen** [redcanari/canari3#25]
Hello,

I'm using `canari==3.1.3` to create local transforms. Id like to give this code to someone else to use my local transforms. 

I understand that I can give the code as a github repo and someone can `python setup.py install` to get the dev environment, but how do I deploy to someone else? Do i just give them the `*.mtz` file? The old `canari` had `canari install-package` but I dont think thats present in this latest release. Would appreciate any help and can contribute documentation back for those having similar issues.

**Comment by allfro** [comment]
Hi there,

You basically have to give them the source code and then ask them to run
canari generate-profile <transform package>. The MTZ is not redistributable
since it is dependant on how the other user installed canari on their
machine. The documentation in the README should have some additional
instruction on how to do that as well.

Cheers

Nadeem

**Comment by zmallen** [comment]
Thanks!
