### ISSUE TITLE
Feature request: Modifying the smaller Entity icon

### ISSUE THREAD

**Issue by maxlandon** [redcanari/canari3#54]
Hello again @allfro ,

I have another wish :) for which I could not find any solution in the Canari documentation:
Maltego Entities basically have 2 icons: the main one, and a smaller one in the bottom right of the main icon.
It would be absolutely fantastic to be able to leverage the second icon (I actually saw some projects using Canari that achieved this).
Do you know if it is possible to do this, and if yes, how ?
Thanks a lot !

**Comment by allfro** [comment]
Yes it is. I would highly suggest looking at the documentation at
Canariproject.com. It has answers to all of the questions you've posted so
far ;). Every entity inherits the icon_url property:
http://www.canariproject.com/en/latest/canari.maltego.message.html#canari.maltego.message.Entity.
Maltego expects this to be the URL of an image.

**Comment by maxlandon** [comment]
Maaaaannnnn after 15 days on this doc I finally found the decorator parameter. So sorry for posting this useless question. 
Nonetheless, is it a problem if I put a list of questions/minor issues from time to time ? I will be as glad to help as I am when using your framework !

**Comment by allfro** [comment]
No problem. Maybe we can create a FAQ

**Comment by maxlandon** [comment]
Hello @allfro, here is a new way to formulate the question pertaining to this thread, which was not completely the one you answered ;)
Maltego-native entities (IPv4 addresses, for example) keep their original icon even when the icon is dynamically changed.
They keep it by putting it in the second, smaller icon slot of the Entity.

This is not reproducible in Canari, even if the order in which 'static icon_url' (defined in the Entity class) and the dynamic setting (any decorator) is correctly enforced.
The result, via Canari, will be an Entity with no icon (a chess pawn icon).

The possibility of mimicking the behavior of native Maltego Entities would be wonderful, as this second, smaller icon_url could be leveraged in many ways.

Have you faced this problem or had this wish when designing Canari ?

**Comment by allfro** [comment]
I think there is a small misunderstanding in terms of how the icon_url property works. I was slightly confused when you mentioned the decorator since that's not how it works. If you want to create a custom entity you need to design it in Maltego first. The design of the entity is totally a Maltego client thing. If you have done that, the reason you are getting the chess piece is because the namespace and entity name you are producing in your Canari transforms is not matching what is wired in the GUI itself. To circumvent any errors I created a `canari generate-entities` command which reads a Maltego profile export containing your custom defined entities with custom icons and produces the equivalent entity class. The small icon you mention is the icon you define in the GUI. The icon_url property pertains to the dynamic icon property which is assigned at runtime like this:

```python
from canari.maltego.entities import Phrase

# ...

    p = Phrase("hello")
    p.icon_url = "http://foo.com/image.png"

# ...
```

I would export your custom entities from Maltego and then use the `canari generate-entities` command to see how each property in the GUI maps to the properties in the python world.
