### ISSUE TITLE
canari does not respect Maltego inheritance model

### ISSUE THREAD

**Issue by trolldbois** [redcanari/canari3#57]
When entities are generated from maltego's mtz, the maltego inheritance model is dropped.

- inherited Fields are missing in canari
- an import of the profile will create entities without inheritance in maltego

**Comment by allfro** [comment]
Is the issue related to the conversion of entity definitions into python code or the execution of transforms or both?

**Comment by trolldbois** [comment]
When the profile is created, the entities included in the profile loose all metadata, including the Maltego inheritance model.
When the `canari create-profile` profile.mtz output is then imported in Maltego, is messes up the Entities metadata in maltego

**Comment by allfro** [comment]
The create-profile command simply copies the entity definitions from the
export. It doesn’t take anything from the python code. The only thing it
does using the code base is define the transforms and transform sets.
Everything else is copied verbatim.

**Comment by cvandeplas** [comment]
It's funny, because I lost a few hours of my life debugging exactly the same issue and writing exactly the same patch.

- The `create-profile` command does not actually copies over all the parameters from the entities. It only copies over the parameters as defined in the `MaltegoEntity(MaltegoElement)` defined in `configuration.py` (line 415).  
- The `add_entity(self, entity)` function in `maltego.py` (line 791), calls `MaltegoEnttiy.parse(entity)`.
- The `parse()` function comes from the inherited `Model` object of the `safedexml` library. This function dynamically imports only the variables from the defined class.

## example
OK, practically. let's look at an exported Entity from Maltego. The MTZ zip archive contains the file `Entities/misp.ThreatActor.entity`:
```xml
<MaltegoEntity id="misp.ThreatActor" displayName="Threat Actor" displayNamePlural="Threat Actors" description="A threat actor" category="MISP" smallIconResource="IntelligenceIcons/threat_actor" largeIconResource="IntelligenceIcons/threat_actor" allowedRoot="true" conversionOrder="2147483647" visible="true">
   <BaseEntities>
      <BaseEntity>misp.MISPGalaxy</BaseEntity>
   </BaseEntities>
   <Properties displayValue="">
      <Groups/>
      <Fields/>
   </Properties>
</MaltegoEntity>
```
Notice there is the `BaseEntities` key in the XML.
When we `create-profile` the code will iterate over all the files and will end up calling `add_entity(self, entity)` function of `maltego.py`. This function calls `MaltegoEntity.parse()` (line 794), and afterwards the `render()` function (line 800) which will generate the following output.
```xml
<?xml version="1.0" ?>
<MaltegoEntity id="misp.ThreatActor" displayName="Threat Actor" displayNamePlural="Threat Actors" description="A threat actor" category="MISP" smallIconResource="IntelligenceIcons/threat_actor" largeIconResource="IntelligenceIcons/threat_actor" allowedRoot="true" conversionOrder="2147483647" visible="true">
	<Properties>
		<Groups />
	</Properties>
</MaltegoEntity>
```
Notice the `BaseEntities` are completely gone.

If we apply @trolldbois 's patch #58 we get correct output: 
```xml
<?xml version="1.0" ?>
<MaltegoEntity id="misp.ThreatActor" displayName="Threat Actor" displayNamePlural="Threat Actors" description="A threat actor" category="MISP" smallIconResource="IntelligenceIcons/threat_actor" largeIconResource="IntelligenceIcons/threat_actor" allowedRoot="true" conversionOrder="2147483647" visible="true">
	<Properties>
		<Groups />
	</Properties>
	<BaseEntities>
		<BaseEntity>misp.MISPGalaxy</BaseEntity>
	</BaseEntities>
</MaltegoEntity>
```

So it would be great if you could merge this PR and release a new version of canari !
Thanks

**Comment by trolldbois** [comment]
#58 was merged
